version:  '3.5'

services:
  mariadb:
    build: requirements/mariadb
  image: mariadb
  container_name: mariadb
  expose:
    - "3306"
  volumes:

networks:
  wpsite:
    driver: bridge

volumes:
  db:
  wp:

