version:  '3.0'

services:
  mariadb:
    build: ./requirements/mariadb
  image: mariadb
  container_name: mariadb
  expose:
    - "3306"
  volumes:
    - db:/var/lib/mysql
  environment:
    - HOST_NAME=${HOST_NAME}
    - HOST_IPv4=${HOST_IPv4}
    - MARIADB_HOST=${MARIADB_HOST}
    - MARIADB_DB=${MARIADB_DB}
    - MARIADB_USER=${MARIADB_USER}
    - MARIADB_PWD=${MARIADB_PWD}
    - MARIADB_ADMIN_USER=${MARIADB_ADMIN_USER}
    - MARIADB_ADMIN_PWD=${MARIADB_ADMIN_PWD}


networks:
  wpsite:
    driver: bridge

volumes:
  db:
  wp:

